"""
convert_models.py — Convert trained models to TFLite + tflite-micro C arrays

Converts all trained models to TFLite (float + int8) and generates
C arrays for embedding in ESP32-S3 firmware (tflite-micro).

License: MIT
"""
import os
import numpy as np
import tensorflow as tf

MODELS_DIR = "models"
FIRMWARE_DIR = "../firmware/hub/models"

def convert_model(h5_path, tflite_path, quantize=True):
    """Convert Keras .h5 model to TFLite."""
    model = tf.keras.models.load_model(h5_path)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    if quantize:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.int8

    tflite_model = converter.convert()
    with open(tflite_path, 'wb') as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"  {tflite_path}: {size_kb:.1f} KB")
    return tflite_model

def generate_c_array(tflite_model, output_path, var_name):
    """Generate C array for tflite-micro."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("/* Auto-generated by convert_models.py */\n")
        f.write(f"/* CardioSync {var_name} (int8 quantized) */\n")
        f.write(f"/* Size: {len(tflite_model)} bytes */\n\n")
        f.write(f'const unsigned char {var_name}[] __PROGMEM = {{\n')
        for i, b in enumerate(tflite_model):
            if i % 12 == 0:
                f.write('  ')
            f.write(f'0x{b:02x}, ')
            if i % 12 == 11:
                f.write('\n')
        f.write('\n};\n\n')
        f.write(f'const unsigned int {var_name}_len = {len(tflite_model)};\n')

def main():
    print("=" * 60)
    print("CardioSync Model Conversion")
    print("=" * 60)

    os.makedirs(MODELS_DIR, exist_ok=True)
    os.makedirs(FIRMWARE_DIR, exist_ok=True)

    # Convert AFib CNN
    if os.path.exists(f"{MODELS_DIR}/afib_cnn.h5"):
        print("\n[1/5] AFib CNN...")
        tflite = convert_model(f"{MODELS_DIR}/afib_cnn.h5",
                               f"{MODELS_DIR}/afib_cnn_int8.tflite")
        generate_c_array(tflite, f"{FIRMWARE_DIR}/afib_cnn_tflite.cc",
                         "afib_cnn_tflite")

    # Convert BP Trend LSTM
    if os.path.exists(f"{MODELS_DIR}/bp_trend_lstm.h5"):
        print("\n[2/5] BP Trend LSTM...")
        tflite = convert_model(f"{MODELS_DIR}/bp_trend_lstm.h5",
                               f"{MODELS_DIR}/bp_trend_lstm.tflite")

    # Convert Sleep Apnea LSTM
    if os.path.exists(f"{MODELS_DIR}/sleep_apnea_lstm.h5"):
        print("\n[3/5] Sleep Apnea LSTM...")
        tflite = convert_model(f"{MODELS_DIR}/sleep_apnea_lstm.h5",
                               f"{MODELS_DIR}/sleep_apnea_lstm.tflite")

    # Convert POTS Detector
    if os.path.exists(f"{MODELS_DIR}/pots_detector.h5"):
        print("\n[4/5] POTS Detector...")
        tflite = convert_model(f"{MODELS_DIR}/pots_detector.h5",
                               f"{MODELS_DIR}/pots_detector.tflite")

    # Stroke Risk XGBoost (already .pkl, no conversion needed)
    if os.path.exists(f"{MODELS_DIR}/stroke_risk_xgb.pkl"):
        print("\n[5/5] Stroke Risk XGBoost (sklearn model, no conversion needed)")

    print("\n" + "=" * 60)
    print("All models converted!")
    print("=" * 60)

if __name__ == "__main__":
    main()