"""
JointSync ML Pipeline — Inflammation Detection (Edge Model for tflite-micro)

Trains and quantizes a small neural network for on-Hub inflammation detection
using bilateral temperature delta, ROM, and HRV.

License: MIT
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import os

# ─────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────

NUM_FEATURES = 4  # temp_normalized, bilateral_delta, rom_normalized, hrv_normalized
EPOCHS = 50
BATCH_SIZE = 128

# ─────────────────────────────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────────────────────────────

def build_inflammation_model():
    """Build a tiny MLP for edge inference."""
    model = keras.Sequential([
        layers.Input(shape=(NUM_FEATURES,)),
        layers.Dense(8, activation='relu'),
        layers.Dense(4, activation='relu'),
        layers.Dense(1, activation='sigmoid'),
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# ─────────────────────────────────────────────────────────────────────
# Synthetic Data Generation
# ─────────────────────────────────────────────────────────────────────

def generate_synthetic_data(n=10000):
    """Generate synthetic inflammation data."""
    np.random.seed(42)

    # Features: [temp_norm, bilateral_delta, rom_norm, hrv_norm]
    X = np.zeros((n, NUM_FEATURES))
    y = np.zeros(n)

    for i in range(n):
        inflamed = np.random.random() < 0.3

        if inflamed:
            # Inflamed joint: higher temp, larger delta, lower ROM, lower HRV
            X[i, 0] = np.random.uniform(0.5, 1.0)   # Normalized temp (32-37°C → 0-1)
            X[i, 1] = np.random.uniform(1.5, 4.0)   # Bilateral delta °C
            X[i, 2] = np.random.uniform(0.0, 0.5)   # Normalized ROM (low)
            X[i, 3] = np.random.uniform(0.0, 0.4)   # Normalized HRV (low)
            y[i] = 1
        else:
            # Normal joint
            X[i, 0] = np.random.uniform(0.0, 0.5)
            X[i, 1] = np.random.uniform(0.0, 1.0)
            X[i, 2] = np.random.uniform(0.5, 1.0)
            X[i, 3] = np.random.uniform(0.4, 1.0)
            y[i] = 0

    return X, y

# ─────────────────────────────────────────────────────────────────────
# Train + Quantize
# ─────────────────────────────────────────────────────────────────────

def train_and_quantize():
    """Train the inflammation model and quantize for tflite-micro."""
    print("=== JointSync Inflammation Detection (Edge) ===")

    # Generate data
    X, y = generate_synthetic_data(10000)
    split = int(0.8 * len(X))
    X_train, X_val = X[:split], X[split:]
    y_train, y_val = y[:split], y[split:]

    print(f"Train: {X_train.shape}, Val: {X_val.shape}")
    print(f"Train inflammation rate: {y_train.mean():.2%}")

    # Build and train
    model = build_inflammation_model()
    model.fit(X_train, y_train, epochs=EPOCHS, batch_size=BATCH_SIZE,
              validation_data=(X_val, y_val), verbose=1)

    # Evaluate
    val_loss, val_acc = model.evaluate(X_val, y_val)
    print(f"Validation accuracy: {val_acc:.4f}")

    # Quantize for tflite-micro
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.int8]

    # Representative dataset for quantization
    def representative_dataset():
        for i in range(100):
            yield [X_train[i:i+1].astype(np.float32)]

    converter.representative_dataset = representative_dataset
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    quantized_model = converter.convert()

    # Save
    os.makedirs("models", exist_ok=True)
    with open("models/inflammation_quant.tflite", "wb") as f:
        f.write(quantized_model)

    # Also save unquantized for comparison
    model.save("models/inflammation_keras.h5")

    # Print model size
    model_size = len(quantized_model)
    print(f"Quantized model size: {model_size} bytes ({model_size/1024:.1f} KB)")
    print("Saved: models/inflammation_quant.tflite")

    # Generate C header for embedding in firmware
    generate_c_header(quantized_model)

    return model

def generate_c_header(model_data, output_path="models/inflammation_model.h"):
    """Generate C header file for embedding in ESP32-S3 firmware."""
    with open(output_path, "w") as f:
        f.write("/* Auto-generated by train_inflammation_tflm.py */\n")
        f.write("/* Inflammation detection model for tflite-micro */\n\n")
        f.write("#ifndef INFLAMMATION_MODEL_H\n#define INFLAMMATION_MODEL_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"const unsigned char inflammation_model_data[] = {{\n")
        for i in range(0, len(model_data), 12):
            chunk = model_data[i:i+12]
            hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"  {hex_vals},\n")
        f.write("};\n\n")
        f.write(f"const unsigned int inflammation_model_len = {len(model_data)};\n\n")
        f.write("#endif /* INFLAMMATION_MODEL_H */\n")

    print(f"C header generated: {output_path} ({len(model_data)} bytes)")

if __name__ == "__main__":
    train_and_quantize()
    print("\nInflammation model training complete!")