/**
 * MigraineSync — Action Plan Screen
 * ===================================
 * License: MIT
 */

import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, StyleSheet, ScrollView, RefreshControl } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { getActionPlan, ActionPlan } from '../services/api';

export default function ActionPlanScreen() {
  const [plan, setPlan] = useState<ActionPlan | null>(null);
  const [refreshing, setRefreshing] = useState(false);

  const fetch = useCallback(async () => {
    try { setPlan(await getActionPlan()); } catch (e) { console.error(e); }
  }, []);

  useEffect(() => { fetch(); const i = setInterval(fetch, 60000); return () => clearInterval(i); }, [fetch]);
  const onRefresh = async () => { setRefreshing(true); await fetch(); setRefreshing(false); };

  const zoneColors = { green: '#27AE60', yellow: '#F39C12', red: '#E74C3C' };
  const zoneIcons = { green: 'checkmark-circle', yellow: 'warning', red: 'alert-circle' };
  const color = zoneColors[plan?.zone || 'green'];

  return (
    <ScrollView style={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}>
      <View style={styles.header}>
        <Text style={styles.title}>Action Plan</Text>
        <Text style={styles.subtitle}>Personalized intervention recommendations</Text>
      </View>

      <View style={[styles.zoneCard, { borderColor: color }]}>
        <Ionicons name={(zoneIcons[plan?.zone || 'green']) as any} size={48} color={color} />
        <Text style={[styles.zoneText, { color }]}>
          {plan?.zone?.toUpperCase() || 'GREEN'} ZONE
        </Text>
        <Text style={styles.riskText}>Current risk: {plan?.risk_score?.toFixed(1) || 0}%</Text>
      </View>

      <View style={styles.stepsCard}>
        <Text style={styles.sectionTitle}>Recommended Steps</Text>
        {plan?.steps.map((step, i) => (
          <View key={i} style={styles.stepRow}>
            <View style={[styles.stepNumber, { backgroundColor: color }]}>
              <Text style={styles.stepNumberText}>{i + 1}</Text>
            </View>
            <Text style={styles.stepText}>{step}</Text>
          </View>
        ))}
      </View>

      <Text style={styles.disclaimer}>
        This action plan is generated by AI and is not a substitute for professional medical advice.
        Always consult your doctor before changing your medication regimen.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#1A1A2E' },
  header: { padding: 20, paddingTop: 50 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#6C5CE7' },
  subtitle: { fontSize: 12, color: '#636E72', marginTop: 4 },
  zoneCard: { margin: 20, padding: 24, borderRadius: 16, backgroundColor: '#16213E', borderWidth: 2, alignItems: 'center' },
  zoneText: { fontSize: 20, fontWeight: 'bold', marginTop: 12 },
  riskText: { fontSize: 14, color: '#636E72', marginTop: 4 },
  stepsCard: { margin: 20, padding: 16, borderRadius: 12, backgroundColor: '#16213E' },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: '#FFFFFF', marginBottom: 16 },
  stepRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 16 },
  stepNumber: { width: 28, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  stepNumberText: { fontSize: 14, fontWeight: 'bold', color: '#FFFFFF' },
  stepText: { flex: 1, fontSize: 14, color: '#A0A0B0', marginLeft: 12, flexWrap: 'wrap' },
  disclaimer: { padding: 20, fontSize: 10, color: '#636E72', textAlign: 'center' },
});