"""
SightSync ML Pipeline — Convert Models for Edge Deployment
===========================================================

Converts trained models to tflite-micro format for ESP32-S3
edge inference (fatigue index, blink anomaly, posture CNN).

License: MIT
"""

import os
import joblib
import numpy as np

MODEL_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "firmware", "hub", "models")
OUTPUT_DIR = os.path.join(MODEL_DIR, "tflite")


def convert_fatigue_index():
    """Convert XGBoost fatigue index model to tflite-compatible C array."""
    print("Converting Fatigue Index model...")
    model_path = os.path.join(MODEL_DIR, "fatigue_index.joblib")
    if not os.path.exists(model_path):
        print("  Model not found — skipping")
        return

    model = joblib.load(model_path)

    # XGBoost → tflite conversion is done via tree-to-tflite
    # For now, export as C header with tree structure
    output_path = os.path.join(OUTPUT_DIR, "fatigue_index_model.h")
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    with open(output_path, "w") as f:
        f.write("/* Auto-generated by convert_models.py */\n")
        f.write("#ifndef FATIGUE_INDEX_MODEL_H\n")
        f.write("#define FATIGUE_INDEX_MODEL_H\n\n")
        f.write(f"/* XGBoost model: {model.n_estimators} trees */\n")
        f.write(f"#define FATIGUE_N_TREES {model.n_estimators}\n")
        f.write(f"#define FATIGUE_N_FEATURES 6\n\n")
        f.write("/* In production: export tree structure as C arrays */\n")
        f.write("/* For now: use heuristic fallback in fatigue_engine.c */\n\n")
        f.write("#endif /* FATIGUE_INDEX_MODEL_H */\n")

    print(f"  Saved: {output_path}")


def convert_blink_anomaly():
    """Convert isolation forest to tflite-compatible format."""
    print("Converting Blink Anomaly model...")
    model_path = os.path.join(MODEL_DIR, "blink_isoforest.joblib")
    if not os.path.exists(model_path):
        print("  Model not found — skipping")
        return

    output_path = os.path.join(OUTPUT_DIR, "blink_anomaly_model.h")
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    with open(output_path, "w") as f:
        f.write("/* Auto-generated by convert_models.py */\n")
        f.write("#ifndef BLINK_ANOMALY_MODEL_H\n")
        f.write("#define BLINK_ANOMALY_MODEL_H\n\n")
        f.write("/* Isolation Forest model — use heuristic in fatigue_engine.c */\n\n")
        f.write("#endif /* BLINK_ANOMALY_MODEL_H */\n")

    print(f"  Saved: {output_path}")


def convert_posture_cnn():
    """Convert PyTorch posture CNN to tflite."""
    print("Converting Posture CNN model...")
    try:
        import torch
        model_path = os.path.join(MODEL_DIR, "posture_cnn.pt")
        if not os.path.exists(model_path):
            print("  Model not found — skipping")
            return

        # Load model architecture + weights
        from train_posture_cnn import PostureCNN
        model = PostureCNN(input_channels=6, sequence_length=125, num_classes=4)
        model.load_state_dict(torch.load(model_path))
        model.eval()

        # Trace and export to ONNX (already done in training)
        # For tflite: ONNX → tflite via onnx2tf or onnx-tf
        onnx_path = os.path.join(MODEL_DIR, "posture_cnn.onnx")
        if os.path.exists(onnx_path):
            print(f"  ONNX already exists: {onnx_path}")
            print("  Use onnx2tf to convert to tflite for ESP32-S3")

    except ImportError:
        print("  PyTorch not available — skipping")


def convert_myopia_lstm():
    """Convert PyTorch myopia LSTM to ONNX (already done in training)."""
    print("Converting Myopia LSTM model...")
    onnx_path = os.path.join(MODEL_DIR, "myopia_lstm.onnx")
    if os.path.exists(onnx_path):
        print(f"  ONNX already exists: {onnx_path}")
    else:
        print("  ONNX not found — run train_myopia_risk.py first")


def main():
    print("=== SightSync Model Conversion ===\n")
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    convert_fatigue_index()
    convert_blink_anomaly()
    convert_posture_cnn()
    convert_myopia_lstm()

    print("\nDone. Copy tflite models to firmware/hub/models/ for edge deployment.")


if __name__ == "__main__":
    main()